### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by carlorosati** [hugomassing/soundcloudArtwork#2]

**Comment by hugomassing** [comment]
Which track do you want to get the URL? Works perfectly for me

**Comment by carlorosati** [comment]
https://soundcloud.com/jaytechmusic/jaytech-endy-free-download

**Comment by hugomassing** [comment]
Looks like SoundCloud has introduced an option for right holders to disable all API access to tracks by default, returning this 403 error when requested has as seen [here](http://stackoverflow.com/questions/36360202/soundcloud-api-urls-timing-out-and-then-returning-error-403-on-about-50-of-trac/36529330#36529330)

Sorry, I can't do anything about this...

**Comment by carlorosati** [comment]
Who says we need API access anyways 😛 

```
document.getElementsByClassName("listenArtworkWrapper")[0].getElementsByClassName("image__full")[0].getAttribute("style").match(/url\(([^)]*)/)[1]
```

**Comment by hugomassing** [comment]
Ahah yeah, I made this project for a friend some times ago! Sad about the direction Soudncloud is taking...
